package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Auto generated by hbm2java
 */
public class Auto  implements java.io.Serializable {


     private Integer idAuto;
     private Proveedor proveedor;
     private TipoAuto tipoAuto;
     private String marca;
     private Integer modelo;
     private Byte cantidad;
     private Double precio;
     private String color;
     private String descripcion;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Auto() 
    {
        proveedor = new Proveedor();
        tipoAuto = new TipoAuto();
    }

    public Auto(Proveedor proveedor, TipoAuto tipoAuto, String marca, Integer modelo, Byte cantidad, Double precio, String color, String descripcion, Set<Venta> ventas) {
       this.proveedor = proveedor;
       this.tipoAuto = tipoAuto;
       this.marca = marca;
       this.modelo = modelo;
       this.cantidad = cantidad;
       this.precio = precio;
       this.color = color;
       this.descripcion = descripcion;
       this.ventas = ventas;
    }
   
    public Integer getIdAuto() {
        return this.idAuto;
    }
    
    public void setIdAuto(Integer idAuto) {
        this.idAuto = idAuto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public TipoAuto getTipoAuto() {
        return this.tipoAuto;
    }
    
    public void setTipoAuto(TipoAuto tipoAuto) {
        this.tipoAuto = tipoAuto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Integer modelo) {
        this.modelo = modelo;
    }
    public Byte getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Byte cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


