package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer idPedido;
     private Proveedor proveedor;
     private TipoAuto tipoAuto;
     private String marca;
     private Integer modelo;
     private Double preciouni;
     private Byte cantidad;
     private Double iva;
     private Double totalPre;
     private String color;
     private Date fechaEla;
     private Date fechaEnt;
     private String descripcion;

    public Pedidos() 
    {
        proveedor = new Proveedor();
        tipoAuto = new TipoAuto();
    }

    public Pedidos(Proveedor proveedor, TipoAuto tipoAuto, String marca, Integer modelo, Double preciouni, Byte cantidad, Double iva, Double totalPre, String color, Date fechaEla, Date fechaEnt, String descripcion) {
       this.proveedor = proveedor;
       this.tipoAuto = tipoAuto;
       this.marca = marca;
       this.modelo = modelo;
       this.preciouni = preciouni;
       this.cantidad = cantidad;
       this.iva = iva;
       this.totalPre = totalPre;
       this.color = color;
       this.fechaEla = fechaEla;
       this.fechaEnt = fechaEnt;
       this.descripcion = descripcion;
    }
   
    public Integer getIdPedido() {
        return this.idPedido;
    }
    
    public void setIdPedido(Integer idPedido) {
        this.idPedido = idPedido;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public TipoAuto getTipoAuto() {
        return this.tipoAuto;
    }
    
    public void setTipoAuto(TipoAuto tipoAuto) {
        this.tipoAuto = tipoAuto;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Integer getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Integer modelo) {
        this.modelo = modelo;
    }
    public Double getPreciouni() {
        return this.preciouni;
    }
    
    public void setPreciouni(Double preciouni) {
        this.preciouni = preciouni;
    }
    public Byte getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Byte cantidad) {
        this.cantidad = cantidad;
    }
    public Double getIva() {
        return this.iva;
    }
    
    public void setIva(Double iva) {
        this.iva = iva;
    }
    public Double getTotalPre() {
        return this.totalPre;
    }
    
    public void setTotalPre(Double totalPre) {
        this.totalPre = totalPre;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Date getFechaEla() {
        return this.fechaEla;
    }
    
    public void setFechaEla(Date fechaEla) {
        this.fechaEla = fechaEla;
    }
    public Date getFechaEnt() {
        return this.fechaEnt;
    }
    
    public void setFechaEnt(Date fechaEnt) {
        this.fechaEnt = fechaEnt;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


