package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private Integer idProveedor;
     private Sexo sexo;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String rfc;
     private String telProveedor;
     private String emailPro;
     private String empresa;
     private String rfcEmpresa;
     private String dirEmpresa;
     private String telEmpresa;
     private String emailEmp;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);
     private Set<Auto> autos = new HashSet<Auto>(0);

    public Proveedor() 
    {
        sexo = new Sexo();
    }

    public Proveedor(Sexo sexo, String nombre, String apaterno, String amaterno, String rfc, String telProveedor, String emailPro, String empresa, String rfcEmpresa, String dirEmpresa, String telEmpresa, String emailEmp, Set<Pedidos> pedidoses, Set<Auto> autos) {
       this.sexo = sexo;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.rfc = rfc;
       this.telProveedor = telProveedor;
       this.emailPro = emailPro;
       this.empresa = empresa;
       this.rfcEmpresa = rfcEmpresa;
       this.dirEmpresa = dirEmpresa;
       this.telEmpresa = telEmpresa;
       this.emailEmp = emailEmp;
       this.pedidoses = pedidoses;
       this.autos = autos;
    }
   
    public Integer getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(Integer idProveedor) {
        this.idProveedor = idProveedor;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getTelProveedor() {
        return this.telProveedor;
    }
    
    public void setTelProveedor(String telProveedor) {
        this.telProveedor = telProveedor;
    }
    public String getEmailPro() {
        return this.emailPro;
    }
    
    public void setEmailPro(String emailPro) {
        this.emailPro = emailPro;
    }
    public String getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(String empresa) {
        this.empresa = empresa;
    }
    public String getRfcEmpresa() {
        return this.rfcEmpresa;
    }
    
    public void setRfcEmpresa(String rfcEmpresa) {
        this.rfcEmpresa = rfcEmpresa;
    }
    public String getDirEmpresa() {
        return this.dirEmpresa;
    }
    
    public void setDirEmpresa(String dirEmpresa) {
        this.dirEmpresa = dirEmpresa;
    }
    public String getTelEmpresa() {
        return this.telEmpresa;
    }
    
    public void setTelEmpresa(String telEmpresa) {
        this.telEmpresa = telEmpresa;
    }
    public String getEmailEmp() {
        return this.emailEmp;
    }
    
    public void setEmailEmp(String emailEmp) {
        this.emailEmp = emailEmp;
    }
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }
    public Set<Auto> getAutos() {
        return this.autos;
    }
    
    public void setAutos(Set<Auto> autos) {
        this.autos = autos;
    }




}


