package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sexo generated by hbm2java
 */
public class Sexo  implements java.io.Serializable {


     private String idSexo;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<Vendedor> vendedors = new HashSet<Vendedor>(0);

    public Sexo() {
    }

	
    public Sexo(String idSexo) {
        this.idSexo = idSexo;
    }
    public Sexo(String idSexo, Set<Cliente> clientes, Set<Proveedor> proveedors, Set<Vendedor> vendedors) {
       this.idSexo = idSexo;
       this.clientes = clientes;
       this.proveedors = proveedors;
       this.vendedors = vendedors;
    }
   
    public String getIdSexo() {
        return this.idSexo;
    }
    
    public void setIdSexo(String idSexo) {
        this.idSexo = idSexo;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<Vendedor> getVendedors() {
        return this.vendedors;
    }
    
    public void setVendedors(Set<Vendedor> vendedors) {
        this.vendedors = vendedors;
    }




}


