package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoCliente generated by hbm2java
 */
public class TipoCliente  implements java.io.Serializable {


     private String idTipoCte;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public TipoCliente() {
    }

	
    public TipoCliente(String idTipoCte) {
        this.idTipoCte = idTipoCte;
    }
    public TipoCliente(String idTipoCte, Set<Cliente> clientes) {
       this.idTipoCte = idTipoCte;
       this.clientes = clientes;
    }
   
    public String getIdTipoCte() {
        return this.idTipoCte;
    }
    
    public void setIdTipoCte(String idTipoCte) {
        this.idTipoCte = idTipoCte;
    }
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


