package model;
// Generated 11/05/2018 01:49:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor  implements java.io.Serializable {


     private Integer idVendedor;
     private Sexo sexo;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private Date fechaNac;
     private Integer edad;
     private String rfc;
     private String telefono;
     private String email;
     private Set<Venta> ventas = new HashSet<Venta>(0);

    public Vendedor() 
    {
        sexo = new Sexo();
    }

    public Vendedor(Sexo sexo, String nombre, String apaterno, String amaterno, Date fechaNac, Integer edad, String rfc, String telefono, String email, Set<Venta> ventas) {
       this.sexo = sexo;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.fechaNac = fechaNac;
       this.edad = edad;
       this.rfc = rfc;
       this.telefono = telefono;
       this.email = email;
       this.ventas = ventas;
    }
   
    public Integer getIdVendedor() {
        return this.idVendedor;
    }
    
    public void setIdVendedor(Integer idVendedor) {
        this.idVendedor = idVendedor;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getRfc() {
        return this.rfc;
    }
    
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set<Venta> getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set<Venta> ventas) {
        this.ventas = ventas;
    }




}


